# Generated by Django 6.0.1 on 2026-03-15 07:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storedquery', '0002_initial'),
        ('watchdog', '0003_signal_signalevent_signalseverity_signaltype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(help_text='The action type registered in ActionRunner', max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='storedquery.savedquery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='automation.automationrule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationActionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('C', 'Completed'), ('F', 'Failed')], default='P', max_length=1)),
                ('error', models.TextField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.automationaction')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_runs', to='automation.automationrun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.CharField(blank=True, choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, null=True)),
                ('trigger_type', models.CharField(choices=[('S', 'Signal'), ('T', 'Time')], default='T', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('is_running', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggers', to='automation.automationrule')),
                ('signal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchdog.signaltype')),
            ],
        ),
        migrations.AddField(
            model_name='automationrun',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationtrigger'),
        ),
        migrations.AddField(
            model_name='automationaction',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='automation.automationtrigger'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'signal_type'], name='automation__trigger_ab5743_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'schedule'], name='automation__trigger_623838_idx'),
        ),
        migrations.AddConstraint(
            model_name='automationtrigger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('schedule__isnull', True), ('signal_type__isnull', False), ('trigger_type', 'S')), models.Q(('schedule__isnull', False), ('signal_type__isnull', True), ('trigger_type', 'T')), _connector='OR'), name='valid_trigger_configuration'),
        ),
    ]
