# Generated by Django 6.0.1 on 2026-03-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
        ('watchdog', '0004_remove_signal_insert_insert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationtrigger',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='automationtrigger',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('name',), name='unique_non_null_name'),
        ),
    ]
