# Generated by Django 6.0.1 on 2026-03-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_automationtrigger_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationaction',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
