# Generated by Django 6.0.1 on 2026-03-24 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modellabels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfieldlabel',
            name='object_id',
        ),
    ]
