# Generated by Django 6.0.1 on 2026-03-26 05:03

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('kyc', '0010_alter_kyccondition_condition_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(limit_choices_to={'reference_set__key': 'countries'}, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='kyc.referencevalue'),
        ),
        migrations.AlterField(
            model_name='company',
            name='registration_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='country',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'reference_set__key': 'countries'}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referencevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('country', 'registration_number')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "company_companyevent" ("country_id", "created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='ea6d2f356ff195cf086143cd82ae2604ba02e83a', operation='INSERT', pgid='pgtrigger_insert_insert_bd932', table='company_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "company_companyevent" ("country_id", "created_at", "id", "is_active", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='158b7e3f095f65b4ac2d260c4cbbbe47e2749c58', operation='UPDATE', pgid='pgtrigger_update_update_f1fc9', table='company_company', when='AFTER')),
        ),
    ]
