# Generated by Django 6.0.1 on 2026-04-24 12:58

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_options_remove_company_insert_insert_and_more'),
        ('kyc', '0013_riskscore_remove_kycrecord_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        migrations.AddField(
            model_name='company',
            name='closeing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_domestic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='opening_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='closeing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='is_domestic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='opening_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'reference_set__key': 'countries'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='kyc.referencevalue'),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'reference_set__key': 'countries'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referencevalue'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "company_companyevent" ("closeing_date", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closeing_date", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='5590ca1b1dd6c39bffcf9899d72095fac218af78', operation='INSERT', pgid='pgtrigger_insert_insert_bd932', table='company_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "company_companyevent" ("closeing_date", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closeing_date", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='ecb1b320e654454bb03e59d28370c5c47cb099e5', operation='UPDATE', pgid='pgtrigger_update_update_f1fc9', table='company_company', when='AFTER')),
        ),
    ]
