# Generated by Django 6.0.1 on 2026-04-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_company_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='opening_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='opening_date',
            field=models.DateField(),
        ),
    ]
