# Generated by Django 6.0.1 on 2026-04-24 13:02

import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_opening_date_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='closeing_date',
            new_name='closing_date',
        ),
        migrations.RenameField(
            model_name='companyevent',
            old_name='closeing_date',
            new_name='closing_date',
        ),
        migrations.AlterField(
            model_name='company',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='companyevent',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "company_companyevent" ("closing_date", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closing_date", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='69cf007ba5f66240fe986951e4d3df54d16934a0', operation='INSERT', pgid='pgtrigger_insert_insert_bd932', table='company_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "company_companyevent" ("closing_date", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closing_date", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='f428a3e9fc46a8e91bb9272438d6e71d6085e72a', operation='UPDATE', pgid='pgtrigger_update_update_f1fc9', table='company_company', when='AFTER')),
        ),
    ]
