# Generated by Django 6.0.1 on 2026-09-30 02:17

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='company',
            name='update_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "company_companyevent" ("closing_date", "company_type_id", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closing_date", NEW."company_type_id", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='5aebe6854138eab52bb50f90c4f3e7917d7eb7ed', operation='INSERT', pgid='pgtrigger_insert_insert_bd932', table='company_company', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='company',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "company_companyevent" ("closing_date", "company_type_id", "country_id", "created_at", "id", "is_active", "is_domestic", "name", "opening_date", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "registration_number", "updated_at") VALUES (NEW."closing_date", NEW."company_type_id", NEW."country_id", NEW."created_at", NEW."id", NEW."is_active", NEW."is_domestic", NEW."name", NEW."opening_date", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."registration_number", NEW."updated_at"); RETURN NULL;', hash='f67b617b12ad48b6218054b8ac400517c0c430a1', operation='UPDATE', pgid='pgtrigger_update_update_f1fc9', table='company_company', when='AFTER')),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.companytype'),
        ),
        migrations.AddField(
            model_name='companyevent',
            name='company_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='company.companytype'),
        ),
    ]
