# Generated by Django 6.0.1 on 2026-02-07 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model', models.CharField(help_text='app_label.ModelName', max_length=100)),
                ('query', models.JSONField()),
                ('is_system', models.BooleanField(default=False, help_text='System-managed default query')),
            ],
        ),
        migrations.CreateModel(
            name='SavedQueryPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('role', 'Role'), ('all', 'All users')], max_length=10)),
                ('target_id', models.CharField(blank=True, help_text='User ID, role code, etc.', max_length=50, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'View'), (2, 'Edit')], default=1)),
            ],
        ),
    ]
