# Generated by Django 6.0.1 on 2026-02-07 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storedquery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquery',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_queries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedquerypermission',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='storedquery.savedquery'),
        ),
        migrations.AddConstraint(
            model_name='savedquery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_system', True), ('owner__isnull', True)), ('is_system', False), _connector='OR'), name='system_queries_have_no_owner'),
        ),
        migrations.AddConstraint(
            model_name='savedquerypermission',
            constraint=models.UniqueConstraint(fields=('query', 'target_type', 'target_id'), name='unique_query_permission'),
        ),
    ]
