# Generated by Django 6.0.1 on 2026-09-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storedquery', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedquery',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='savedquery',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
