# Generated by Django 6.0.1 on 2026-03-07 15:23

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='person',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='person',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personevent',
            name='nationality',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "person_personevent" ("created_at", "date_of_birth", "first_name", "id", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date_of_birth", NEW."first_name", NEW."id", NEW."last_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='3cac42fb54f3b7fc54a067a6be2f6bd5e4e2c8d3', operation='INSERT', pgid='pgtrigger_insert_insert_46ba1', table='person_person', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "person_personevent" ("created_at", "date_of_birth", "first_name", "id", "last_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date_of_birth", NEW."first_name", NEW."id", NEW."last_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='a32f5b08455056385186b7ab0f6bf34dd0d472e8', operation='UPDATE', pgid='pgtrigger_update_update_70e1e', table='person_person', when='AFTER')),
        ),
    ]
