# Generated by Django 6.0.1 on 2026-09-16 21:15

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_remove_person_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='person',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='person',
            name='update_update',
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personevent',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "person_personevent" ("created_at", "date_of_birth", "date_of_death", "first_name", "id", "last_name", "middle_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date_of_birth", NEW."date_of_death", NEW."first_name", NEW."id", NEW."last_name", NEW."middle_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='e89222ea2f79d4adf7c70e78931bade4e63e4aeb', operation='INSERT', pgid='pgtrigger_insert_insert_46ba1', table='person_person', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='person',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "person_personevent" ("created_at", "date_of_birth", "date_of_death", "first_name", "id", "last_name", "middle_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."date_of_birth", NEW."date_of_death", NEW."first_name", NEW."id", NEW."last_name", NEW."middle_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='8e98ef9b794b1984f120c4dd5e735c329ca106c9', operation='UPDATE', pgid='pgtrigger_update_update_70e1e', table='person_person', when='AFTER')),
        ),
    ]
