# Generated by Django 6.0.1 on 2026-09-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_person_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='personevent',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
