# Generated by Django 6.0.1 on 2026-01-13 00:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('is_terminal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.alertreason')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.alertseverity')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.alertstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alertreason',
            name='default_severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_for_reasons', to='watchdog.alertseverity'),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.UUIDField()),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='watchdog.alert')),
                ('reason', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.alertreason')),
                ('severity', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.alertseverity')),
                ('status', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.alertstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "watchdog_alertevent" ("created_at", "id", "message", "object_id", "object_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "severity_id", "status_id", "triggered_at", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."message", NEW."object_id", NEW."object_type", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_id", NEW."severity_id", NEW."status_id", NEW."triggered_at", NEW."updated_at"); RETURN NULL;', hash='fb713e5ef54f8a77e51529ce83ff8c814b418c9f', operation='INSERT', pgid='pgtrigger_insert_insert_2a042', table='watchdog_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "watchdog_alertevent" ("created_at", "id", "message", "object_id", "object_type", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "severity_id", "status_id", "triggered_at", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."message", NEW."object_id", NEW."object_type", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_id", NEW."severity_id", NEW."status_id", NEW."triggered_at", NEW."updated_at"); RETURN NULL;', hash='50d3e291ca91bead2a1d9ac2782d70c6084c2d23', operation='UPDATE', pgid='pgtrigger_update_update_1cbd4', table='watchdog_alert', when='AFTER')),
        ),
    ]
