# Generated by Django 6.0.1 on 2026-01-13 00:36

from django.db import migrations

def seed_reference_data(apps, schema_editor):
    AlertStatus = apps.get_model("watchdog", "AlertStatus")
    AlertSeverity = apps.get_model("watchdog", "AlertSeverity")
    AlertReason = apps.get_model("watchdog", "AlertReason")

    # -----------------------
    # Alert Severity
    # -----------------------
    severities = [
        {"code": "low", "name": "Low", "rank": 10},
        {"code": "medium", "name": "Medium", "rank": 20},
        {"code": "high", "name": "High", "rank": 30},
        {"code": "critical", "name": "Critical", "rank": 40},
    ]

    severity_map = {}
    for data in severities:
        obj, _ = AlertSeverity.objects.update_or_create(
            code=data["code"],
            defaults=data,
        )
        severity_map[data["code"]] = obj

    # -----------------------
    # Alert Status
    # -----------------------
    statuses = [
        {"code": "open", "name": "Open", "is_terminal": False},
        {"code": "acknowledged", "name": "Acknowledged", "is_terminal": False},
        {"code": "resolved", "name": "Resolved", "is_terminal": True},
    ]

    for data in statuses:
        AlertStatus.objects.update_or_create(
            code=data["code"],
            defaults=data,
        )

    # -----------------------
    # Alert Reasons
    # -----------------------
    reasons = [
        {
            "code": "KYC_EXPIRED",
            "name": "KYC expired",
            "description": "An approved KYC record has expired",
            "default_severity": severity_map["high"],
        },
        {
            "code": "OWNERSHIP_THRESHOLD",
            "name": "Ownership threshold exceeded",
            "description": "Ownership exceeds regulatory threshold",
            "default_severity": severity_map["critical"],
        },
        {
            "code": "RAPID_CHANGES",
            "name": "Rapid changes detected",
            "description": "Multiple changes in a short time window",
            "default_severity": severity_map["medium"],
        },
    ]

    for data in reasons:
        AlertReason.objects.update_or_create(
            code=data["code"],
            defaults={
                "name": data["name"],
                "description": data["description"],
                "default_severity": data["default_severity"],
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_reference_data)
    ]
