# Generated by Django 6.0.1 on 2026-02-07 03:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('watchdog', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignalSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SignalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='alert',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='alertevent',
            name='object_type',
        ),
        migrations.AddField(
            model_name='alert',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alertevent',
            name='content_type',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "watchdog_alertevent" ("content_type_id", "created_at", "id", "message", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "severity_id", "status_id", "triggered_at", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."message", NEW."object_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reason_id", NEW."severity_id", NEW."status_id", NEW."triggered_at", NEW."updated_at"); RETURN NULL;', hash='46f1156c3f29a68ba5e04c0b5677fb209be177ed', operation='INSERT', pgid='pgtrigger_insert_insert_2a042', table='watchdog_alert', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='alert',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "watchdog_alertevent" ("content_type_id", "created_at", "id", "message", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reason_id", "severity_id", "status_id", "triggered_at", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."message", NEW."object_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reason_id", NEW."severity_id", NEW."status_id", NEW."triggered_at", NEW."updated_at"); RETURN NULL;', hash='ca9f9923298b4410cd85b5697246c91dee080136', operation='UPDATE', pgid='pgtrigger_update_update_1cbd4', table='watchdog_alert', when='AFTER')),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='watchdog.signal'),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='severity',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.signalseverity'),
        ),
        migrations.AddField(
            model_name='signal',
            name='severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.signalseverity'),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='signal_type',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='watchdog.signaltype'),
        ),
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='watchdog.signaltype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "watchdog_signalevent" ("created_at", "id", "metadata", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resolved_at", "severity_id", "signal_type_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."metadata", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."resolved_at", NEW."severity_id", NEW."signal_type_id", NEW."updated_at"); RETURN NULL;', hash='4f841a7294f0137511986ccf07d2c9d7561a051b', operation='INSERT', pgid='pgtrigger_insert_insert_57bc9', table='watchdog_signal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "watchdog_signalevent" ("created_at", "id", "metadata", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "resolved_at", "severity_id", "signal_type_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."metadata", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."resolved_at", NEW."severity_id", NEW."signal_type_id", NEW."updated_at"); RETURN NULL;', hash='9162d53ad8e010dda2c3f52eb75c69cc683e1eeb', operation='UPDATE', pgid='pgtrigger_update_update_0f2e0', table='watchdog_signal', when='AFTER')),
        ),
    ]
