# Generated by Django 6.0.1 on 2026-03-15 07:30

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('watchdog', '0003_signal_signalevent_signalseverity_signaltype_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='signal',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='signal',
            name='update_update',
        ),
        migrations.RenameField(
            model_name='signal',
            old_name='resolved_at',
            new_name='processed_at',
        ),
        migrations.RenameField(
            model_name='signalevent',
            old_name='resolved_at',
            new_name='processed_at',
        ),
        migrations.AddField(
            model_name='signal',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='signal',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='signalevent',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "watchdog_signalevent" ("content_type_id", "created_at", "id", "metadata", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_at", "severity_id", "signal_type_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."metadata", NEW."object_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."processed_at", NEW."severity_id", NEW."signal_type_id", NEW."updated_at"); RETURN NULL;', hash='d854038ff485caeb92527a99cfee68981a1f187f', operation='INSERT', pgid='pgtrigger_insert_insert_57bc9', table='watchdog_signal', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='signal',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "watchdog_signalevent" ("content_type_id", "created_at", "id", "metadata", "object_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "processed_at", "severity_id", "signal_type_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."metadata", NEW."object_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."processed_at", NEW."severity_id", NEW."signal_type_id", NEW."updated_at"); RETURN NULL;', hash='bf8f15f19c35442c0f033696725f5cbefc5a6b9f', operation='UPDATE', pgid='pgtrigger_update_update_0f2e0', table='watchdog_signal', when='AFTER')),
        ),
    ]
