# Generated by Django 6.0.1 on 2026-05-22 17:41

from django.db import migrations


def seed_reference_data(apps, schema_editor):
    AlertSeverity = apps.get_model("watchdog", "AlertSeverity")
    AlertReason = apps.get_model("watchdog", "AlertReason")

    try:
        eventDefaultSeverity = AlertSeverity.objects.get(code="low")
    except AlertSeverity.DoesNotExist as e:
        raise ValueError(f"Default Event Severity of 'low' does not exist: {e}")

    reasons = [
        {
            "code": "EVENT",
            "name": "Event",
            "description": "An Alert for an Event",
            "default_severity": eventDefaultSeverity,
        }
    ]

    for data in reasons:
        AlertReason.objects.update_or_create(
            code=data["code"],
            defaults={
                "name": data["name"],
                "description": data["description"],
                "default_severity": data["default_severity"],
                "is_active": True,
            },
        )

class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0004_remove_signal_insert_insert_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_reference_data)
    ]
