# Generated by Django 6.0.1 on 2026-05-22 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0005_seed_more_alert_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['triggered_at']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='triggered_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
