# Generated by Django 6.0.1 on 2026-05-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchdog', '0006_alter_alert_options_alter_alert_triggered_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['triggered_at', '-severity']},
        ),
    ]
