# Generated by Django 6.0.1 on 2026-04-17 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalparams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booleanvalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
        migrations.AddField(
            model_name='datetimevalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
        migrations.AddField(
            model_name='floatvalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
        migrations.AddField(
            model_name='intvalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
        migrations.AddField(
            model_name='uuidvalue',
            name='parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter'),
        ),
    ]
