# Generated by Django 6.0.1 on 2026-04-24 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalparams', '0002_booleanvalue_parameter_datetimevalue_parameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalparameter',
            name='type',
            field=models.CharField(choices=[('S', 'String'), ('I', 'Integer'), ('F', 'Float'), ('B', 'Boolean'), ('U', 'UUID'), ('D', 'Datetime'), ('J', 'JSON')], default='S', max_length=1),
        ),
        migrations.CreateModel(
            name='JsonValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('parameter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='globalparams.globalparameter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
