# Generated by Django 6.0.1 on 2026-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('globalparams', '0004_alter_globalparameter_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='globalparameter',
            name='valid_generic_relation',
        ),
        migrations.AlterField(
            model_name='globalparameter',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='globalparameter',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_type__isnull', True), ('object_id__isnull', True)), models.Q(('content_type__isnull', False), ('object_id__isnull', False)), _connector='OR'), name='valid_generic_relation_int'),
        ),
    ]
