# Generated by Django 6.0.1 on 2026-01-13 00:05

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('kyc', '0001_initial'),
        ('person', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycrecord',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to='person.person'),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='person.person'),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycrecord'),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='status',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycstatus'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_records', to='kyc.kycstatus'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationshipevent',
            name='company',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='company.company'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationshipevent',
            name='person',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='person.person'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationshipevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationshipevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.personcompanyrelationship'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationshipevent',
            name='role',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.relationshiprole'),
        ),
        migrations.AddField(
            model_name='personcompanyrelationship',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='kyc.relationshiprole'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "notes", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."notes", NEW."person_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='ab2b7df6c1b10b05cac51358440c3c2782084b3b', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "notes", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."notes", NEW."person_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='9288adc6cab42800f32ce96463bdd35877fa2b66', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='personcompanyrelationship',
            unique_together={('person', 'company', 'role', 'start_date')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='personcompanyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_personcompanyrelationshipevent" ("company_id", "created_at", "end_date", "id", "ownership_percentage", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "updated_at") VALUES (NEW."company_id", NEW."created_at", NEW."end_date", NEW."id", NEW."ownership_percentage", NEW."person_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."start_date", NEW."updated_at"); RETURN NULL;', hash='0df08ca4d34ad6c9c66e9f1a76f4fa652c1cb57a', operation='INSERT', pgid='pgtrigger_insert_insert_32689', table='kyc_personcompanyrelationship', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='personcompanyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_personcompanyrelationshipevent" ("company_id", "created_at", "end_date", "id", "ownership_percentage", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "updated_at") VALUES (NEW."company_id", NEW."created_at", NEW."end_date", NEW."id", NEW."ownership_percentage", NEW."person_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."start_date", NEW."updated_at"); RETURN NULL;', hash='dd910da50138191dcf2f941e30bc502882685ebd', operation='UPDATE', pgid='pgtrigger_update_update_73703', table='kyc_personcompanyrelationship', when='AFTER')),
        ),
    ]
