# Generated by Django 6.0.1 on 2026-01-13 00:48

from django.db import migrations

def seed_relationship_roles(apps, schema_editor):
    Role = apps.get_model("kyc", "RelationshipRole")

    roles = [
        {"code": "director", "name": "Director"},
        {"code": "owner", "name": "Owner"},
        {"code": "employee", "name": "Employee"},
        {"code": "beneficial_owner", "name": "Beneficial Owner"},
    ]

    for data in roles:
        Role.objects.update_or_create(
            code=data["code"],
            defaults=data,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_relationship_roles)
    ]
