# Generated by Django 6.0.1 on 2026-02-07 03:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_seed_relationship_roles'),
        ('person', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KycAnswerEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KycAnswerOptionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('S', 'single'), ('M', 'multi')], max_length=1)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KycQuestionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('key', models.SlugField(db_index=False)),
                ('label', models.CharField(max_length=255)),
                ('answer_type', models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('S', 'single'), ('M', 'multi')], max_length=1)),
                ('required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KycQuestionOptionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."person_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='f9e4cd0e9ebf099a6ba8cf45e93e2d9b39667b10', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "person_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."person_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='b4e5cc68dc0959c4caf1f3de597588428e4f3487', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='kycrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('person',), name='one_current_kyc_per_person'),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='kyc_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kyc.kycrecord'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='kyc_record',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycrecord'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycanswer'),
        ),
        migrations.AddField(
            model_name='kycansweroption',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_options', to='kyc.kycanswer'),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='answer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycanswer'),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycansweroption'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.kycquestion'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "id", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."answer_type", NEW."id", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."required"); RETURN NULL;', hash='b0702b95a861c12e87303343543b71c37081b886', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "id", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."answer_type", NEW."id", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."required"); RETURN NULL;', hash='1ec38122d2b22dbbaf14696fc7c72c18c4b455c4', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='option',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestionoption'),
        ),
        migrations.AddField(
            model_name='kycansweroption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyc.kycquestionoption'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_option',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestionoption'),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyc.kycquestionoption'),
        ),
        migrations.AddField(
            model_name='kycquestionoptionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycquestionoptionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycquestionoption'),
        ),
        migrations.AddField(
            model_name='kycquestionoptionevent',
            name='question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='kycquestionoption',
            unique_together={('question', 'value')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestionoption',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionoptionevent" ("id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "value") VALUES (NEW."id", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."value"); RETURN NULL;', hash='7c8ccb9c1d437ec8cad1610059da0e79a61019e1', operation='INSERT', pgid='pgtrigger_insert_insert_77a4d', table='kyc_kycquestionoption', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestionoption',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionoptionevent" ("id", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "value") VALUES (NEW."id", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."value"); RETURN NULL;', hash='ae772eb3c73235eef12a01a0b52fe41fb390de51', operation='UPDATE', pgid='pgtrigger_update_update_99303', table='kyc_kycquestionoption', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='kycansweroption',
            unique_together={('answer', 'option')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycansweroption',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycansweroptionevent" ("answer_id", "id", "option_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answer_id", NEW."id", NEW."option_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id"); RETURN NULL;', hash='0dc252f86519c87cbb0fe5862481b40fc39106bb', operation='INSERT', pgid='pgtrigger_insert_insert_3a4c8', table='kyc_kycansweroption', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycansweroption',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycansweroptionevent" ("answer_id", "id", "option_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id") VALUES (NEW."answer_id", NEW."id", NEW."option_id", _pgh_attach_context(), NOW(), \'update\', NEW."id"); RETURN NULL;', hash='7b98b67cf43ba69c9e9a14960848178a10352a9c', operation='UPDATE', pgid='pgtrigger_update_update_9b42c', table='kyc_kycansweroption', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='kycanswer',
            unique_together={('kyc_record', 'question')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "value_bool", "value_number", "value_option_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."value_bool", NEW."value_number", NEW."value_option_id", NEW."value_text"); RETURN NULL;', hash='803978ecf1078dea73c51c8d4445b00221b444e6', operation='INSERT', pgid='pgtrigger_insert_insert_f1c4b', table='kyc_kycanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "value_bool", "value_number", "value_option_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."value_bool", NEW."value_number", NEW."value_option_id", NEW."value_text"); RETURN NULL;', hash='e3ba151834c95151ab5e07c930228ffc0717404b', operation='UPDATE', pgid='pgtrigger_update_update_2bb6b', table='kyc_kycanswer', when='AFTER')),
        ),
    ]
