# Generated by Django 6.0.1 on 2026-03-01 17:06

import django.db.models.deletion
import kyc.models
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycanswer_kycanswerevent_kycansweroption_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycAnswerAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='kyc/answers/%Y/%m/%d/', validators=[kyc.models.validate_file])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['created_at', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KycAnswerAttachmentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='kyc/answers/%Y/%m/%d/', validators=[kyc.models.validate_file])),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.BigIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='requires_document',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "id", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."id", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='5a8e7ce417c7910e59ef16a0d6c21102f484652e', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "id", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."id", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='6bf1e42ea86052b43708ae26a3cf63e81e88ea3e', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kycanswerattachment',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='kyc.kycanswer'),
        ),
        migrations.AddField(
            model_name='kycanswerattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycanswerattachmentevent',
            name='answer',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycanswer'),
        ),
        migrations.AddField(
            model_name='kycanswerattachmentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycanswerattachmentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycanswerattachment'),
        ),
        migrations.AddField(
            model_name='kycanswerattachmentevent',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswerattachment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycanswerattachmentevent" ("answer_id", "content_type", "created_at", "description", "file", "id", "original_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "updated_at", "uploaded_by_id") VALUES (NEW."answer_id", NEW."content_type", NEW."created_at", NEW."description", NEW."file", NEW."id", NEW."original_name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."size", NEW."updated_at", NEW."uploaded_by_id"); RETURN NULL;', hash='25d0ee11b6ef103bd060984e2044b6b7ec15f42b', operation='INSERT', pgid='pgtrigger_insert_insert_162c1', table='kyc_kycanswerattachment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswerattachment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycanswerattachmentevent" ("answer_id", "content_type", "created_at", "description", "file", "id", "original_name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "size", "updated_at", "uploaded_by_id") VALUES (NEW."answer_id", NEW."content_type", NEW."created_at", NEW."description", NEW."file", NEW."id", NEW."original_name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."size", NEW."updated_at", NEW."uploaded_by_id"); RETURN NULL;', hash='bede54c5581de894102e13c807779fa8f5c3908d', operation='UPDATE', pgid='pgtrigger_update_update_cefe4', table='kyc_kycanswerattachment', when='AFTER')),
        ),
    ]
