# Generated by Django 6.0.1 on 2026-03-03 23:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycanswerattachment_kycanswerattachmentevent_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('show', 'Show question'), ('require', 'Require answer'), ('block', 'Block submission'), ('validate', 'Custom validation')], max_length=20)),
                ('rule', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KycConditionDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, help_text='If false, missing value does not invalidate rule')),
            ],
        ),
        migrations.CreateModel(
            name='KycConditionDependencyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('is_required', models.BooleanField(default=True, help_text='If false, missing value does not invalidate rule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycConditionEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('condition_type', models.CharField(choices=[('show', 'Show question'), ('require', 'Require answer'), ('block', 'Block submission'), ('validate', 'Custom validation')], max_length=20)),
                ('rule', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('is_repeatable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KycQuestionGroupEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('key', models.SlugField(db_index=False)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('is_repeatable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycRuleConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('date', 'Date'), ('bool', 'Boolean')], max_length=20)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='KycRuleConstantEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('key', models.SlugField(db_index=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('date', 'Date'), ('bool', 'Boolean')], max_length=20)),
                ('value_int', models.IntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('value_string', models.CharField(blank=True, max_length=255, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSetEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('key', models.SlugField(db_index=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceValueEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='kycquestionoption',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kycquestionoption',
            name='question',
        ),
        migrations.RemoveField(
            model_name='kycanswerevent',
            name='value_option',
        ),
        migrations.RemoveField(
            model_name='kycquestionoptionevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='kycansweroptionevent',
            name='option',
        ),
        migrations.RemoveField(
            model_name='kycquestionoptionevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='kycquestionoptionevent',
            name='question',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycanswer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycanswer',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycansweroption',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycansweroption',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='update_update',
        ),
        migrations.AlterUniqueTogether(
            name='kycanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='repeat_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_phone',
            field=models.CharField(blank=True, help_text='Enter phone number in international format', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='repeat_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_phone',
            field=models.CharField(blank=True, help_text='Enter phone number in international format', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='kycansweroption',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='is_repeatable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kyc.kycquestion'),
        ),
        migrations.AlterField(
            model_name='kycquestion',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address')], max_length=1),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "repeat_index", "value_bool", "value_date", "value_date_from", "value_date_to", "value_email", "value_number", "value_phone", "value_reference_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."repeat_index", NEW."value_bool", NEW."value_date", NEW."value_date_from", NEW."value_date_to", NEW."value_email", NEW."value_number", NEW."value_phone", NEW."value_reference_id", NEW."value_text"); RETURN NULL;', hash='fe2998d2062201ed16dbdc476a8f00c2b88685d7', operation='INSERT', pgid='pgtrigger_insert_insert_f1c4b', table='kyc_kycanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "repeat_index", "value_bool", "value_date", "value_date_from", "value_date_to", "value_email", "value_number", "value_phone", "value_reference_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."repeat_index", NEW."value_bool", NEW."value_date", NEW."value_date_from", NEW."value_date_to", NEW."value_email", NEW."value_number", NEW."value_phone", NEW."value_reference_id", NEW."value_text"); RETURN NULL;', hash='cc63ae136764a0a3dcf9ad2d009b3a9809eef99e', operation='UPDATE', pgid='pgtrigger_update_update_2bb6b', table='kyc_kycanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycansweroption',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycansweroptionevent" ("answer_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_value_id") VALUES (NEW."answer_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_value_id"); RETURN NULL;', hash='c6e9c6b86500a09bf8a20c8177f2de4e6d65ac65', operation='INSERT', pgid='pgtrigger_insert_insert_3a4c8', table='kyc_kycansweroption', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycansweroption',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycansweroptionevent" ("answer_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_value_id") VALUES (NEW."answer_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_value_id"); RETURN NULL;', hash='0e5ceef8ff1ab656ea409325490c15861f149260', operation='UPDATE', pgid='pgtrigger_update_update_9b42c', table='kyc_kycansweroption', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "group_id", "id", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='f6cdabd5ecde0405650ed4404a27e3b3dcc6cc14', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "group_id", "id", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='ea52909e30b5b67958d2635afec919be036768f7', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kyccondition',
            name='target_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycconditiondependency',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='kyc.kyccondition'),
        ),
        migrations.AddField(
            model_name='kycconditiondependency',
            name='source_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_conditions', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycconditiondependencyevent',
            name='condition',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kyccondition'),
        ),
        migrations.AddField(
            model_name='kycconditiondependencyevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycconditiondependencyevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycconditiondependency'),
        ),
        migrations.AddField(
            model_name='kycconditiondependencyevent',
            name='source_question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycconditionevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycconditionevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kyccondition'),
        ),
        migrations.AddField(
            model_name='kycconditionevent',
            name='target_question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestion'),
        ),
        migrations.AddField(
            model_name='kycconditiondependencyevent',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestiongroup'),
        ),
        migrations.AddField(
            model_name='kycconditiondependency',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.kycquestiongroup'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestiongroup',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestiongroupevent" ("id", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."required"); RETURN NULL;', hash='8f4dad217c6dd882f07e31c66512659d1d0b4c1a', operation='INSERT', pgid='pgtrigger_insert_insert_bf965', table='kyc_kycquestiongroup', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestiongroup',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestiongroupevent" ("id", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."required"); RETURN NULL;', hash='81066c1088fccb8d850f46f04c586072f28ea56e', operation='UPDATE', pgid='pgtrigger_update_update_6b9eb', table='kyc_kycquestiongroup', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kyc.kycquestiongroup'),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.kycquestiongroup'),
        ),
        migrations.AddField(
            model_name='kycquestiongroupevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycquestiongroupevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycquestiongroup'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycruleconstant',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycruleconstantevent" ("description", "id", "is_active", "key", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "value_bool", "value_date", "value_float", "value_int", "value_string", "value_type") VALUES (NEW."description", NEW."id", NEW."is_active", NEW."key", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at", NEW."value_bool", NEW."value_date", NEW."value_float", NEW."value_int", NEW."value_string", NEW."value_type"); RETURN NULL;', hash='d6f6b41309a17c59c7757d66da3a1cd9bef13429', operation='INSERT', pgid='pgtrigger_insert_insert_9595d', table='kyc_kycruleconstant', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycruleconstant',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycruleconstantevent" ("description", "id", "is_active", "key", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "value_bool", "value_date", "value_float", "value_int", "value_string", "value_type") VALUES (NEW."description", NEW."id", NEW."is_active", NEW."key", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at", NEW."value_bool", NEW."value_date", NEW."value_float", NEW."value_int", NEW."value_string", NEW."value_type"); RETURN NULL;', hash='c5734c7ab242478d6c612b2dc1b31501fbb38bc6', operation='UPDATE', pgid='pgtrigger_update_update_5def1', table='kyc_kycruleconstant', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kycruleconstantevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='kycruleconstantevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.kycruleconstant'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referenceset',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_referencesetevent" ("created_at", "description", "id", "is_active", "key", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_active", NEW."key", NEW."name", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."version"); RETURN NULL;', hash='f24efc8ebcbd806118e098fcb4fd557e82ca42f7', operation='INSERT', pgid='pgtrigger_insert_insert_bccd6', table='kyc_referenceset', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referenceset',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_referencesetevent" ("created_at", "description", "id", "is_active", "key", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "version") VALUES (NEW."created_at", NEW."description", NEW."id", NEW."is_active", NEW."key", NEW."name", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."version"); RETURN NULL;', hash='5fe8dda963fce6050f5c945bec2ec414de09c9bd', operation='UPDATE', pgid='pgtrigger_update_update_71b3c', table='kyc_referenceset', when='AFTER')),
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='reference_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='kyc.referenceset'),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='reference_set',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referenceset'),
        ),
        migrations.AddField(
            model_name='referencesetevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='referencesetevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.referenceset'),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='reference_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kyc.referenceset'),
        ),
        migrations.AlterUniqueTogether(
            name='kycansweroption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='single_answers', to='kyc.referencevalue'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_reference',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referencevalue'),
        ),
        migrations.AddField(
            model_name='kycansweroption',
            name='reference_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='multi_answers', to='kyc.referencevalue'),
        ),
        migrations.AddField(
            model_name='kycansweroptionevent',
            name='reference_value',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referencevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='kycansweroption',
            unique_together={('answer', 'reference_value')},
        ),
        migrations.AddIndex(
            model_name='kycansweroption',
            index=models.Index(fields=['answer'], name='kyc_kycansw_answer__c5738a_idx'),
        ),
        migrations.AddIndex(
            model_name='kycansweroption',
            index=models.Index(fields=['reference_value'], name='kyc_kycansw_referen_4f5043_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycanswer',
            constraint=models.UniqueConstraint(fields=('kyc_record', 'question', 'repeat_index'), name='unique_answer_instance'),
        ),
        migrations.AddField(
            model_name='referencevalueevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='referencevalueevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='kyc.referencevalue'),
        ),
        migrations.AddField(
            model_name='referencevalueevent',
            name='reference_set',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.referenceset'),
        ),
        migrations.DeleteModel(
            name='KycQuestionOptionEvent',
        ),
        migrations.RemoveField(
            model_name='kycanswer',
            name='value_option',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kyccondition',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycconditionevent" ("condition_type", "created_at", "description", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "rule", "target_question_id") VALUES (NEW."condition_type", NEW."created_at", NEW."description", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."priority", NEW."rule", NEW."target_question_id"); RETURN NULL;', hash='64c26ffa57c58d0a6b18e40ff9860bc2c42abafd', operation='INSERT', pgid='pgtrigger_insert_insert_8a5be', table='kyc_kyccondition', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kyccondition',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycconditionevent" ("condition_type", "created_at", "description", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "rule", "target_question_id") VALUES (NEW."condition_type", NEW."created_at", NEW."description", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."priority", NEW."rule", NEW."target_question_id"); RETURN NULL;', hash='e299a7aacb64898b0b92828c1c0580e2e94f4c06', operation='UPDATE', pgid='pgtrigger_update_update_1431d', table='kyc_kyccondition', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='kycconditiondependency',
            unique_together={('condition', 'source_question', 'group')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycconditiondependency',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycconditiondependencyevent" ("condition_id", "group_id", "id", "is_required", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_question_id") VALUES (NEW."condition_id", NEW."group_id", NEW."id", NEW."is_required", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."source_question_id"); RETURN NULL;', hash='013b27ad7bfdb90176f23887ad8f24b6c8fcde30', operation='INSERT', pgid='pgtrigger_insert_insert_2ddb2', table='kyc_kycconditiondependency', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycconditiondependency',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycconditiondependencyevent" ("condition_id", "group_id", "id", "is_required", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "source_question_id") VALUES (NEW."condition_id", NEW."group_id", NEW."id", NEW."is_required", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."source_question_id"); RETURN NULL;', hash='f5bd19310179c6b324663dc65d165e1e232c58dc', operation='UPDATE', pgid='pgtrigger_update_update_73a74', table='kyc_kycconditiondependency', when='AFTER')),
        ),
        migrations.AlterUniqueTogether(
            name='referencevalue',
            unique_together={('reference_set', 'code')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencevalue',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_referencevalueevent" ("code", "id", "is_active", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id") VALUES (NEW."code", NEW."id", NEW."is_active", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_set_id"); RETURN NULL;', hash='31e135d5a774ba263542b16e7834005fbd275c7e', operation='INSERT', pgid='pgtrigger_insert_insert_c49fa', table='kyc_referencevalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referencevalue',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_referencevalueevent" ("code", "id", "is_active", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id") VALUES (NEW."code", NEW."id", NEW."is_active", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_set_id"); RETURN NULL;', hash='44832e4223267539fe79b2572fc4b3329d60985f', operation='UPDATE', pgid='pgtrigger_update_update_a729d', table='kyc_referencevalue', when='AFTER')),
        ),
        migrations.RemoveField(
            model_name='kycansweroption',
            name='option',
        ),
        migrations.DeleteModel(
            name='KycQuestionOption',
        ),
    ]
