# Generated by Django 6.0.1 on 2026-03-07 14:28

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kyccondition_kycconditiondependency_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personcompanyrelationship',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationship',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationship',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationship',
            name='role',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationshipevent',
            name='pgh_obj',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationshipevent',
            name='company',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationshipevent',
            name='person',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationshipevent',
            name='pgh_context',
        ),
        migrations.RemoveField(
            model_name='personcompanyrelationshipevent',
            name='role',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='kycrecord',
            name='one_current_kyc_per_person',
        ),
        migrations.RemoveField(
            model_name='kycrecordevent',
            name='person',
        ),
    ]
