# Generated by Django 6.0.1 on 2026-03-07 14:28

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_alter_personcompanyrelationship_unique_together_and_more'),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycquestion',
            name='party_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kyc_questions', to='party.partytype'),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='party_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.partytype'),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_records', to='party.party'),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='party',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.party'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "group_id", "id", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='93973d7e2464314b6c927ae32240062d26d29770', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "group_id", "id", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='8c0c6b3566a95babf267a851c05ff508ad34120d', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='1df156db27e1ce5d24c0e11aaccba6b108ba8497', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."risk_score", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='cc62328f889a05c13b89b608c2b68ae88ab081bd', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='kycrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('party',), name='one_current_kyc_per_party'),
        ),
        migrations.DeleteModel(
            name='PersonCompanyRelationship',
        ),
        migrations.DeleteModel(
            name='PersonCompanyRelationshipEvent',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='person',
        ),
    ]
