# Generated by Django 6.0.1 on 2026-03-24 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_seed_kyc_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyccondition',
            name='condition_type',
            field=models.CharField(choices=[('S', 'Show question'), ('R', 'Require answer'), ('B', 'Block submission'), ('V', 'Custom validation')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kycconditionevent',
            name='condition_type',
            field=models.CharField(choices=[('S', 'Show question'), ('R', 'Require answer'), ('B', 'Block submission'), ('V', 'Custom validation')], max_length=1),
        ),
    ]
