# Generated by Django 6.0.1 on 2026-03-26 07:21

from django.db import migrations

def seed_more_statuses(apps, schema_editor):
    KYCStatus = apps.get_model("kyc", "KYCStatus")

    new_statuses = [
        ("created", "Created"),
        ("under_review", "Under Review"),
        ("requires_update", "Requires Update"),
        ("on_hold", "On Hold"),
    ]

    for code, name in new_statuses:
        obj, created = KYCStatus.objects.get_or_create(
            code=code.lower(),
            defaults={"name": name}
        )
        # Optional: ensure name is up-to-date if someone changed it manually
        if not created and obj.name != name:
            obj.name = name
            obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_alter_kyccondition_condition_type_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_more_statuses, migrations.RunPython.noop),
    ]
