# Generated by Django 6.0.1 on 2026-03-31 06:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
        ('kyc', '0011_seed_more_kyc_statuses'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycanswer',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycanswer',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycanswer',
            name='value_encrypt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encrypt.encryptionvalue'),
        ),
        migrations.AddField(
            model_name='kycanswerevent',
            name='value_encrypt',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='encrypt.encryptionvalue'),
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='encrypt_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='encrypt.encryptiontype'),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='encrypt_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='encrypt.encryptiontype'),
        ),
        migrations.AlterField(
            model_name='kycquestion',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='required',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "repeat_index", "value_bool", "value_date", "value_date_from", "value_date_to", "value_email", "value_encrypt_id", "value_number", "value_phone", "value_reference_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."question_id", NEW."repeat_index", NEW."value_bool", NEW."value_date", NEW."value_date_from", NEW."value_date_to", NEW."value_email", NEW."value_encrypt_id", NEW."value_number", NEW."value_phone", NEW."value_reference_id", NEW."value_text"); RETURN NULL;', hash='c03ce475a3f7634a21f926102cd1664ddb68a46a', operation='INSERT', pgid='pgtrigger_insert_insert_f1c4b', table='kyc_kycanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycanswer',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycanswerevent" ("id", "kyc_record_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "question_id", "repeat_index", "value_bool", "value_date", "value_date_from", "value_date_to", "value_email", "value_encrypt_id", "value_number", "value_phone", "value_reference_id", "value_text") VALUES (NEW."id", NEW."kyc_record_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."question_id", NEW."repeat_index", NEW."value_bool", NEW."value_date", NEW."value_date_from", NEW."value_date_to", NEW."value_email", NEW."value_encrypt_id", NEW."value_number", NEW."value_phone", NEW."value_reference_id", NEW."value_text"); RETURN NULL;', hash='2446b1a44aeee91d1efa2971f1b4f9eb8a0d337d', operation='UPDATE', pgid='pgtrigger_update_update_2bb6b', table='kyc_kycanswer', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "encrypt_type_id", "group_id", "id", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."encrypt_type_id", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='5f6c9297ceff872e5b7640f12ef1889496bcfec8', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "encrypt_type_id", "group_id", "id", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."encrypt_type_id", NEW."group_id", NEW."id", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='2efbc615ea8b049b4554b8a70f48a816299dbe91', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
    ]
