# Generated by Django 6.0.1 on 2026-04-24 12:58

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0012_remove_kycanswer_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('label', models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='H', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.AlterField(
            model_name='kycquestion',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('A', 'text_area'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('A', 'text_area'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address')], max_length=1),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score_id", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."risk_score_id", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='a72c3a7f6b3cb371d679deab81782dc660e474cd', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "risk_score_id", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."risk_score_id", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='2d6669ddeb68a582756b27794948cb7f9dc8744c', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
        migrations.AlterField(
            model_name='kycrecord',
            name='risk_score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.riskscore'),
        ),
        migrations.AlterField(
            model_name='kycrecordevent',
            name='risk_score',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.riskscore'),
        ),
    ]
