# Generated by Django 6.0.1 on 2026-04-25 21:26

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0013_riskscore_remove_kycrecord_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskscore',
            options={'ordering': ['-created_at']},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='kycrecord',
            name='risk_score',
        ),
        migrations.RemoveField(
            model_name='kycrecordevent',
            name='risk_score',
        ),
        migrations.AddField(
            model_name='riskscore',
            name='kyc_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to='kyc.kycrecord'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='967640ac5adf6ec68b6d4b48995f83a8b7449b72', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verified_at") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verified_at"); RETURN NULL;', hash='863e611cf40aeb52765e213a927308039f527906', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
    ]
