# Generated by Django 6.0.1 on 2026-05-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0014_alter_riskscore_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycquestion',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('A', 'text_area'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address'), ('F', 'file')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kycquestion',
            name='key',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='kycquestion',
            name='label',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='answer_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('A', 'text_area'), ('B', 'bool'), ('S', 'single'), ('M', 'multi'), ('D', 'date'), ('R', 'date_range'), ('P', 'phone_number'), ('E', 'email_address'), ('F', 'file')], max_length=1),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='key',
            field=models.SlugField(db_index=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='kycquestionevent',
            name='label',
            field=models.CharField(max_length=500),
        ),
    ]
