# Generated by Django 6.0.1 on 2026-05-19 01:21

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0015_alter_kycquestion_answer_type_alter_kycquestion_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='verification_type',
            field=models.CharField(choices=[('M', 'Manual'), ('S', 'System'), ('N', 'Not Set')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='verification_type',
            field=models.CharField(choices=[('M', 'Manual'), ('S', 'System'), ('N', 'Not Set')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verification_type", "verified_at", "verified_by_id") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verification_type", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='a730b9b87dd8418efd026e61c430d9fa5f4dfd9d', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verification_type", "verified_at", "verified_by_id") VALUES (NEW."created_at", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verification_type", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='1a3746cf54e6734ebc1b28376df2dccc7fae98e0', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
    ]
