# Generated by Django 6.0.1 on 2026-05-29 19:28

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0016_remove_kycrecord_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycrecord',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycrecord',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycrecordevent',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycrecordevent" ("created_at", "expiry_date", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verification_type", "verified_at", "verified_by_id") VALUES (NEW."created_at", NEW."expiry_date", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verification_type", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='9379bea2c23d2652b72b8a497e460a755ff2eac4', operation='INSERT', pgid='pgtrigger_insert_insert_b8209', table='kyc_kycrecord', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycrecord',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycrecordevent" ("created_at", "expiry_date", "id", "is_current", "notes", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status_id", "updated_at", "verification_type", "verified_at", "verified_by_id") VALUES (NEW."created_at", NEW."expiry_date", NEW."id", NEW."is_current", NEW."notes", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status_id", NEW."updated_at", NEW."verification_type", NEW."verified_at", NEW."verified_by_id"); RETURN NULL;', hash='941b79a58627f62aeaef6fd0f7cb36fa9f2eaf53', operation='UPDATE', pgid='pgtrigger_update_update_a4182', table='kyc_kycrecord', when='AFTER')),
        ),
    ]
