# Generated by Django 6.0.1 on 2026-09-23 17:41

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0017_remove_kycrecord_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestion',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestiongroup',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='kycquestiongroup',
            name='update_update',
        ),
        migrations.AddField(
            model_name='kycquestion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kycquestionevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kycquestiongroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='kycquestiongroupevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "encrypt_type_id", "group_id", "id", "is_active", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."encrypt_type_id", NEW."group_id", NEW."id", NEW."is_active", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='8f285017b969157440217d53347cddfb7e174bef', operation='INSERT', pgid='pgtrigger_insert_insert_d2f0c', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestion',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestionevent" ("answer_type", "encrypt_type_id", "group_id", "id", "is_active", "is_repeatable", "key", "label", "order", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "reference_set_id", "required", "requires_document") VALUES (NEW."answer_type", NEW."encrypt_type_id", NEW."group_id", NEW."id", NEW."is_active", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", NEW."party_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."reference_set_id", NEW."required", NEW."requires_document"); RETURN NULL;', hash='10af3f40d0573b2e946e283c970e68e23b35d6b1', operation='UPDATE', pgid='pgtrigger_update_update_70720', table='kyc_kycquestion', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestiongroup',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "kyc_kycquestiongroupevent" ("id", "is_active", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."id", NEW."is_active", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."required"); RETURN NULL;', hash='a0d7f8ded5e12b7ed418002369e460dc1fdb74f5', operation='INSERT', pgid='pgtrigger_insert_insert_bf965', table='kyc_kycquestiongroup', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='kycquestiongroup',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "kyc_kycquestiongroupevent" ("id", "is_active", "is_repeatable", "key", "label", "order", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "required") VALUES (NEW."id", NEW."is_active", NEW."is_repeatable", NEW."key", NEW."label", NEW."order", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."required"); RETURN NULL;', hash='0901c48fe0698370f85ba0e69d36b6b3c48695af', operation='UPDATE', pgid='pgtrigger_update_update_6b9eb', table='kyc_kycquestiongroup', when='AFTER')),
        ),
    ]
