# Generated by Django 6.0.1 on 2026-03-31 06:34

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptionTypeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('tag', models.BinaryField()),
                ('key_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncryptionValueEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('tag', models.BinaryField()),
                ('key_id', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptiontype',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "encrypt_encryptiontypeevent" ("created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='4e63cff39eb7cb381ef2c52af6b0bdfc3106044f', operation='INSERT', pgid='pgtrigger_insert_insert_1cb9d', table='encrypt_encryptiontype', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptiontype',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "encrypt_encryptiontypeevent" ("created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='f49d9059c5623a37e81874d1744aeb0c2951d3ff', operation='UPDATE', pgid='pgtrigger_update_update_50711', table='encrypt_encryptiontype', when='AFTER')),
        ),
        migrations.AddField(
            model_name='encryptiontypeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='encryptiontypeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='encrypt.encryptiontype'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptionvalue',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "encrypt_encryptionvalueevent" ("ciphertext", "created_at", "id", "key_id", "nonce", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag", "updated_at") VALUES (NEW."ciphertext", NEW."created_at", NEW."id", NEW."key_id", NEW."nonce", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='1b996a444f8b7e718c00112a1ebd77f29c194a88', operation='INSERT', pgid='pgtrigger_insert_insert_aae72', table='encrypt_encryptionvalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptionvalue',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "encrypt_encryptionvalueevent" ("ciphertext", "created_at", "id", "key_id", "nonce", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "tag", "updated_at") VALUES (NEW."ciphertext", NEW."created_at", NEW."id", NEW."key_id", NEW."nonce", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."tag", NEW."updated_at"); RETURN NULL;', hash='f2a9a095e44b83abd38da5f71b6049add0b8922c', operation='UPDATE', pgid='pgtrigger_update_update_ffa70', table='encrypt_encryptionvalue', when='AFTER')),
        ),
        migrations.AddField(
            model_name='encryptionvalueevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='encryptionvalueevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='encrypt.encryptionvalue'),
        ),
    ]
