# Generated by Django 6.0.1 on 2026-04-09 04:55

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='encryptiontype',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='encryptiontype',
            name='update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='encryptionvalue',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='encryptionvalue',
            name='update_update',
        ),
        migrations.RenameField(
            model_name='encryptionvalue',
            old_name='nonce',
            new_name='dek',
        ),
        migrations.RenameField(
            model_name='encryptionvalueevent',
            old_name='nonce',
            new_name='dek',
        ),
        migrations.RemoveField(
            model_name='encryptionvalue',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='encryptionvalueevent',
            name='tag',
        ),
        migrations.AddField(
            model_name='encryptiontype',
            name='algorithm',
            field=models.CharField(choices=[('AES256_GCM', 'AES256_GCM'), ('XCHACHA20_POLY1305', 'XCHACHA20_POLY1305')], default='AES256_GCM', max_length=50),
        ),
        migrations.AddField(
            model_name='encryptiontype',
            name='status',
            field=models.CharField(choices=[('S', 'Safe'), ('D', 'Deprecated'), ('U', 'Unsafe'), ('E', 'Experimental')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='encryptiontypeevent',
            name='algorithm',
            field=models.CharField(choices=[('AES256_GCM', 'AES256_GCM'), ('XCHACHA20_POLY1305', 'XCHACHA20_POLY1305')], default='AES256_GCM', max_length=50),
        ),
        migrations.AddField(
            model_name='encryptiontypeevent',
            name='status',
            field=models.CharField(choices=[('S', 'Safe'), ('D', 'Deprecated'), ('U', 'Unsafe'), ('E', 'Experimental')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='encryptionvalue',
            name='data_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('D', 'date'), ('P', 'phone_number'), ('E', 'email_address')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='encryptionvalue',
            name='encrypt_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='encrypt.encryptiontype'),
        ),
        migrations.AddField(
            model_name='encryptionvalueevent',
            name='data_type',
            field=models.CharField(choices=[('N', 'number'), ('T', 'text'), ('B', 'bool'), ('D', 'date'), ('P', 'phone_number'), ('E', 'email_address')], default='T', max_length=1),
        ),
        migrations.AddField(
            model_name='encryptionvalueevent',
            name='encrypt_type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='encrypt.encryptiontype'),
        ),
        migrations.AlterField(
            model_name='encryptionvalue',
            name='key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encryptionvalueevent',
            name='key_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptiontype',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "encrypt_encryptiontypeevent" ("algorithm", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."algorithm", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='5e50306b141b2f2afd04397124bfe5e02039ccaf', operation='INSERT', pgid='pgtrigger_insert_insert_1cb9d', table='encrypt_encryptiontype', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptiontype',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "encrypt_encryptiontypeevent" ("algorithm", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."algorithm", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='652f866d631fb2f8e681f809ea0092aa13bfadff', operation='UPDATE', pgid='pgtrigger_update_update_50711', table='encrypt_encryptiontype', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptionvalue',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "encrypt_encryptionvalueevent" ("ciphertext", "created_at", "data_type", "dek", "encrypt_type_id", "id", "key_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."ciphertext", NEW."created_at", NEW."data_type", NEW."dek", NEW."encrypt_type_id", NEW."id", NEW."key_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='db94642556c8afab81e9cfe965f9d993195c502b', operation='INSERT', pgid='pgtrigger_insert_insert_aae72', table='encrypt_encryptionvalue', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='encryptionvalue',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "encrypt_encryptionvalueevent" ("ciphertext", "created_at", "data_type", "dek", "encrypt_type_id", "id", "key_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."ciphertext", NEW."created_at", NEW."data_type", NEW."dek", NEW."encrypt_type_id", NEW."id", NEW."key_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='d5bed613a394921bd1523c888c1158ffc46569b0', operation='UPDATE', pgid='pgtrigger_update_update_ffa70', table='encrypt_encryptionvalue', when='AFTER')),
        ),
    ]
