# Generated by Django 6.0.1 on 2026-04-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encrypt', '0002_remove_encryptiontype_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptionvalue',
            name='ciphertext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryptionvalue',
            name='dek',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryptionvalueevent',
            name='ciphertext',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='encryptionvalueevent',
            name='dek',
            field=models.TextField(),
        ),
    ]
