# Generated by Django 6.0.1 on 2026-03-07 14:28

import django.db.models.deletion
import django.utils.timezone
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kyc', '0007_alter_personcompanyrelationship_unique_together_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('serializer_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('party_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='party.partytype')),
            ],
        ),
        migrations.CreateModel(
            name='PartyRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='party.party')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='kyc.relationshiprole')),
                ('target_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='party.party')),
            ],
            options={
                'unique_together': {('party', 'target_party', 'role', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='PartyRelationshipEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.party')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='party.partyrelationship')),
                ('role', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='kyc.relationshiprole')),
                ('target_party', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.party')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='contenttypes.contenttype')),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='party.party')),
                ('party_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.partytype')),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipevent" ("created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='096c278a55dac9d0c9e1f8e85446c7968efbcf13', operation='INSERT', pgid='pgtrigger_insert_insert_85daf', table='party_partyrelationship', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipevent" ("created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='41dbdf2da9fe987382aab25f08fb293db8d0c4f0', operation='UPDATE', pgid='pgtrigger_update_update_9f9a3', table='party_partyrelationship', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_party_entity'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='party',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyevent" ("content_type_id", "created_at", "display_name", "id", "is_active", "object_id", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."display_name", NEW."id", NEW."is_active", NEW."object_id", NEW."party_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='00cf93b0284b345e7c330fe2c14a9e74a9fe3e40', operation='INSERT', pgid='pgtrigger_insert_insert_e10a6', table='party_party', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='party',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyevent" ("content_type_id", "created_at", "display_name", "id", "is_active", "object_id", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."display_name", NEW."id", NEW."is_active", NEW."object_id", NEW."party_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='de1485387b60a6ea29c7975ace658a8a8517a2a0', operation='UPDATE', pgid='pgtrigger_update_update_61975', table='party_party', when='AFTER')),
        ),
    ]
