# Generated by Django 6.0.1 on 2026-03-16 19:40

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_seed_party_types'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='party',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='party',
            name='update_update',
        ),
        migrations.RenameField(
            model_name='party',
            old_name='display_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='partyevent',
            old_name='display_name',
            new_name='name',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='party',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyevent" ("content_type_id", "created_at", "id", "is_active", "name", "object_id", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."is_active", NEW."name", NEW."object_id", NEW."party_type_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='60403eae8c73e71f50a9e298d595414dc9b7e454', operation='INSERT', pgid='pgtrigger_insert_insert_e10a6', table='party_party', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='party',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyevent" ("content_type_id", "created_at", "id", "is_active", "name", "object_id", "party_type_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."content_type_id", NEW."created_at", NEW."id", NEW."is_active", NEW."name", NEW."object_id", NEW."party_type_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='b10fd8f2144528d76e75e50cb8bec8290aa4af5e', operation='UPDATE', pgid='pgtrigger_update_update_61975', table='party_party', when='AFTER')),
        ),
    ]
