# Generated by Django 6.0.1 on 2026-08-18 07:27

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_alter_party_name_alter_partyevent_name_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='update_update',
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partyrelationshipevent',
            name='contact',
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='f6a56599a0a2c8eb194dd448134fba0cfb2c287b', operation='INSERT', pgid='pgtrigger_insert_insert_85daf', table='party_partyrelationship', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='714bb1c7ac38364dbf2e2a6aa6b96f83dc52dcf9', operation='UPDATE', pgid='pgtrigger_update_update_9f9a3', table='party_partyrelationship', when='AFTER')),
        ),
    ]
