# Generated by Django 6.0.1 on 2026-09-16 21:15

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_remove_partyrelationship_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='update_update',
        ),
        migrations.AddField(
            model_name='partyrelationship',
            name='share_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Of Shares'),
        ),
        migrations.AddField(
            model_name='partyrelationshipevent',
            name='share_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percentage Of Shares'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "share_percentage", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."share_percentage", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='69151670a11be01c6ee544b740f0b49a3446236c', operation='INSERT', pgid='pgtrigger_insert_insert_85daf', table='party_partyrelationship', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "share_percentage", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."share_percentage", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='0c067de843ea5d108fa0d85a82c63229a2d1f3f4', operation='UPDATE', pgid='pgtrigger_update_update_9f9a3', table='party_partyrelationship', when='AFTER')),
        ),
    ]
