# Generated by Django 6.0.1 on 2026-09-23 13:50

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0017_remove_kycrecord_insert_insert_and_more'),
        ('party', '0006_remove_partyrelationship_insert_insert_and_more'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRelationshipCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PartyRelationshipMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRelationshipMetadataCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartyRelationshipMetadataCodeEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartyRelationshipMetadataEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationship',
            name='update_update',
        ),
        migrations.AlterUniqueTogether(
            name='partyrelationship',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='partyrelationshipevent',
            name='share_percentage',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='f6a56599a0a2c8eb194dd448134fba0cfb2c287b', operation='INSERT', pgid='pgtrigger_insert_insert_85daf', table='party_partyrelationship', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationship',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipevent" ("contact", "created_at", "end_date", "id", "party_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "role_id", "start_date", "target_party_id", "updated_at") VALUES (NEW."contact", NEW."created_at", NEW."end_date", NEW."id", NEW."party_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."role_id", NEW."start_date", NEW."target_party_id", NEW."updated_at"); RETURN NULL;', hash='714bb1c7ac38364dbf2e2a6aa6b96f83dc52dcf9', operation='UPDATE', pgid='pgtrigger_update_update_9f9a3', table='party_partyrelationship', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.UniqueConstraint(fields=('party', 'target_party', 'role', 'start_date'), name='unique_party_relationship'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationship',
            constraint=models.CheckConstraint(condition=models.Q(('party', models.F('target_party')), _negated=True), name='prevent_self_relationship'),
        ),
        migrations.AddConstraint(
            model_name='partyrelationshipcode',
            constraint=models.CheckConstraint(condition=models.Q(('code__gte', 1)), name='code_gte_1'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadata',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='party.partyrelationship'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacode',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_codes', to='party.partyrelationshipcode'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacode',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='party.partyrelationshipmetadata'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacodeevent',
            name='code',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.partyrelationshipcode'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacodeevent',
            name='metadata',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.partyrelationshipmetadata'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacodeevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadatacodeevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='party.partyrelationshipmetadatacode'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='party.partyrelationshipmetadata'),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='relationship',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='party.partyrelationship'),
        ),
        migrations.RemoveField(
            model_name='partyrelationship',
            name='share_percentage',
        ),
        migrations.AddConstraint(
            model_name='partyrelationshipmetadata',
            constraint=models.UniqueConstraint(fields=('relationship',), name='unique_metadata_per_relationship'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "updated_at") VALUES (NEW."created_at", NEW."details", NEW."id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relationship_id", NEW."updated_at"); RETURN NULL;', hash='977a32c61bd9fb5db4c5627eb57e8db121aa1bb2', operation='INSERT', pgid='pgtrigger_insert_insert_d2dc6', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "updated_at") VALUES (NEW."created_at", NEW."details", NEW."id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relationship_id", NEW."updated_at"); RETURN NULL;', hash='80b4c40871b9e49fc5f525913d84653e2eb7125c', operation='UPDATE', pgid='pgtrigger_update_update_0aeb1', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='partyrelationshipmetadatacode',
            constraint=models.UniqueConstraint(fields=('metadata', 'code'), name='unique_metadata_code'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadatacode',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipmetadatacodeevent" ("code_id", "created_at", "id", "metadata_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."code_id", NEW."created_at", NEW."id", NEW."metadata_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='53fe75dd6965f543c6c53c122c8ad721c651b6d0', operation='INSERT', pgid='pgtrigger_insert_insert_af5d2', table='party_partyrelationshipmetadatacode', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadatacode',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipmetadatacodeevent" ("code_id", "created_at", "id", "metadata_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."code_id", NEW."created_at", NEW."id", NEW."metadata_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='cc35a925e0fa941f59f2c57d8a87861162833c95', operation='UPDATE', pgid='pgtrigger_update_update_0a823', table='party_partyrelationshipmetadatacode', when='AFTER')),
        ),
    ]
