# Generated by Django 6.0.1 on 2026-10-02 03:54

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_partyrelationshipcode_partyrelationshipmetadata_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationshipmetadata',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationshipmetadata',
            name='update_update',
        ),
        migrations.RemoveConstraint(
            model_name='partyrelationshipmetadata',
            name='unique_metadata_per_relationship',
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadata',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "share_percentage", "updated_at") VALUES (NEW."created_at", NEW."details", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relationship_id", NEW."share_percentage", NEW."updated_at"); RETURN NULL;', hash='83abb504eb90e0d765a5ddd450393ae21b420009', operation='INSERT', pgid='pgtrigger_insert_insert_d2dc6', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "share_percentage", "updated_at") VALUES (NEW."created_at", NEW."details", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relationship_id", NEW."share_percentage", NEW."updated_at"); RETURN NULL;', hash='c87ff9f619a431ae0f85c2cc47758aa5f9e3b256', operation='UPDATE', pgid='pgtrigger_update_update_0aeb1', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='partyrelationshipmetadata',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('relationship',), name='unique_active_metadata_per_relationship'),
        ),
    ]
