# Generated by Django 6.0.1 on 2026-10-02 13:05

import django.core.validators
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_remove_partyrelationshipmetadata_insert_insert_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationshipmetadata',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='partyrelationshipmetadata',
            name='update_update',
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadata',
            name='voting_rights_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='partyrelationshipmetadataevent',
            name='voting_rights_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "share_percentage", "updated_at", "voting_rights_percentage") VALUES (NEW."created_at", NEW."details", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."relationship_id", NEW."share_percentage", NEW."updated_at", NEW."voting_rights_percentage"); RETURN NULL;', hash='ec57377bd5503c71fecf1a5fc3ab6103ca6256a9', operation='INSERT', pgid='pgtrigger_insert_insert_d2dc6', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='partyrelationshipmetadata',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "party_partyrelationshipmetadataevent" ("created_at", "details", "id", "is_active", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_id", "share_percentage", "updated_at", "voting_rights_percentage") VALUES (NEW."created_at", NEW."details", NEW."id", NEW."is_active", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."relationship_id", NEW."share_percentage", NEW."updated_at", NEW."voting_rights_percentage"); RETURN NULL;', hash='3c2639b6be1ac6316e281b2573ad0f0c22d9722c', operation='UPDATE', pgid='pgtrigger_update_update_0aeb1', table='party_partyrelationshipmetadata', when='AFTER')),
        ),
    ]
