# Generated by Django 6.0.1 on 2026-03-15 07:30

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Cancelled'), ('F', 'Finished')], default='S', max_length=20)),
                ('organizer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AgendaEventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable name for the event type, e.g., 'Meeting'.", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this event type represents.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agenda Event Type',
                'verbose_name_plural': 'Agenda Event Types',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='agenda_agen_name_212154_idx'), models.Index(fields=['is_active'], name='agenda_agen_is_acti_12f4d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgendaEventEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Cancelled'), ('F', 'Finished')], default='S', max_length=20)),
                ('organizer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL)),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='agenda.agendaevent')),
                ('event_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='agenda.agendaeventtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agendaevent',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda_events', to='agenda.agendaeventtype'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['start_time'], name='agenda_agen_start_t_60066e_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['end_time'], name='agenda_agen_end_tim_313252_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['status'], name='agenda_agen_status_933142_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaevent',
            index=models.Index(fields=['start_time', 'end_time'], name='agenda_agen_start_t_20ffcd_idx'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='agendaevent',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "agenda_agendaeventevent" ("all_day", "created_at", "description", "end_time", "event_type_id", "id", "location", "organizer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time", "status", "title", "updated_at") VALUES (NEW."all_day", NEW."created_at", NEW."description", NEW."end_time", NEW."event_type_id", NEW."id", NEW."location", NEW."organizer_id", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."start_time", NEW."status", NEW."title", NEW."updated_at"); RETURN NULL;', hash='5e54b98bbbdad06a3939ad4fca139d3c497beea2', operation='INSERT', pgid='pgtrigger_insert_insert_e2a42', table='agenda_agendaevent', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='agendaevent',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "agenda_agendaeventevent" ("all_day", "created_at", "description", "end_time", "event_type_id", "id", "location", "organizer_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "start_time", "status", "title", "updated_at") VALUES (NEW."all_day", NEW."created_at", NEW."description", NEW."end_time", NEW."event_type_id", NEW."id", NEW."location", NEW."organizer_id", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."start_time", NEW."status", NEW."title", NEW."updated_at"); RETURN NULL;', hash='c07437880e5f1e53e659509288bce2aa81875db0', operation='UPDATE', pgid='pgtrigger_update_update_40baa', table='agenda_agendaevent', when='AFTER')),
        ),
    ]
