# Generated by Django 6.0.1 on 2026-05-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaeventtype',
            name='code',
            field=models.CharField(default='test', help_text='A code for the internal system to identify the data row without ambiguous spaces', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
