# Generated by Django 6.0.1 on 2026-05-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_agendaeventtype_code'),
        ('watchdog', '0006_alter_alert_options_alter_alert_triggered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaeventevent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendaeventevent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgendaEventTypeAlertSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('measurement', models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], default='D', max_length=1)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_event_alert_schedule', to='agenda.agendaeventtype')),
                ('severity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watchdog.alertseverity')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event_type', 'value', 'measurement'), name='unique_type_value_measurement')],
            },
        ),
    ]
